### ISSUE TITLE
Account Balance Sorunu

### ISSUE THREAD

**Issue by digitallartist** [onurgozupek/btcturkpro#4]
Merhabalar

Son dönemde getBalance ile hiçbir veri gelmiyor. Şu uyarı oluşuyor.
Undefined property: stdClass::$data in btcturkpro.class.php on line 170

Sunucu zaman farklarından kaynaklı olabilir mi? Gerçi bu hariç herşey sorunsuz çalışıyor.

**Comment by onurgozupek** [comment]
getBalances() olarak denediniz mi?

**Comment by digitallartist** [comment]
Evet zaten getBalances olarak deniyorum.

Gelen sonuç şu..

object(stdClass)#25 (3) {
  ["success"]=>
  bool(true)
  ["message"]=>
  string(28) "Unauthorized - Invalid Nonce"
  ["code"]=>
  int(1037)
}
